CREATE TABLE IF NOT EXISTS galaxies(
    ID TEXT PRIMARY KEY,
    RA FLOAT,
    DEC FLOAT,
    Re FLOAT,
    z FLOAT,
    Mstar FLOAT,
    u_mag FLOAT,
    g_mag FLOAT,
    r_mag FLOAT,
    i_mag FLOAT,
    z_mag FLOAT,
    GAL_MU_E_R FLOAT,
    Ellipticity_r FLOAT,
    RS_member INTEGER,
    r_on_rtwo FLOAT,
    ClusterName TEXT,
    ClusterMember INTEGER, 
    GAL_MU_E_U FLOAT,
    GAL_MU_0_U FLOAT,
    GAL_MU_E_G FLOAT,
    GAL_MU_0_G FLOAT,
    GAL_MU_0_R FLOAT,
    GAL_MU_E_I FLOAT,
    GAL_MU_0_I FLOAT,
    GAL_MU_E_Z FLOAT,
    GAL_MU_0_Z FLOAT,
    SersicIndex_r FLOAT,
    MassHIpred FLOAT,
    WALLABYflag INTEGER,
    Dingoflag INTEGER,
    g_m_i FLOAT,
    IFU_diam_2Re FLOAT,
    GAL_MU_R_at_2Re FLOAT,
    GAL_MU_R_at_3Re FLOAT,
    MW_analogue INTEGER,
    EO_wind_galaxy INTEGER,
    priority INTEGER,
    N_observations_to_complete INTEGER,
    bad_class INTEGER,
    Field TEXT,
    Region TEXT,
    FOREIGN KEY ([ID]) REFERENCES "targets" ([ID])
                ON DELETE NO ACTION ON UPDATE NO ACTION
    )